name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            # prepare work catalogue
            if [ ! -d docker_cicd_awsec2 ]; then
              git clone https://github.com/AD2000X/docker_cicd_awsec2.git
            fi
            cd docker_cicd_awsec2
            git pull origin main

            # Rebuild Docker
            docker rm -f flask-app || true
            docker build -t flask-app .
            docker run -d -p 80:5000 --name flask-app flask-app