name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.AWS_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Connect & Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            # prepare work catalogue
            if [ ! -d docker_cicd_awsec2 ]; then
              git clone https://github.com/AD2000X/docker_cicd_awsec2.git
            fi
            cd docker_cicd_awsec2
            git pull origin main

            # Rebuilf Docker
            docker rm -f flask-app || true
            docker build -t flask-app .
            docker run -d -p 80:5000 --name flask-app flask-app
          EOF
